spring.application.name=academia

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework=ERROR
logging.level.org.springframework.security=TRACE

jwt.secret=${JWT_SECRET}
jwt.expiration=64800000